# resource directories
data_dir: "data/"

# logging, see https://docs.python.org/3/library/logging.config.html#logging-config-fileformat
logging:
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    simpleExample:
      level: DEBUG
      handlers: [console]
      propagate: no
  root:
    level: DEBUG
    handlers: [console]

## web app/API settings
api:
  port: 8050 
  host: "0.0.0.0"
  # to specify a custom default header in the response
  #header: 
  log_level: "debug"
  reload: false
  # the following is used in the generated API documentation
  version: "0.2"
  name: "KISH web app and API"
  description: "Keeping It Simple is Hard"
  api_route: ""

  # default admin super-user when not existing, admin_email must be an email and password must be kept secret 
  admin: "admin@admin.com"
  admin_password: "administrator"
  # pass phrase for signing reset and verification password token (choose something strong and keep it secret)
  passphrase: ""
  # lifetime in seconds of reset and verification token
  lifetime: 86400

  # this must be kept secured
  oauth:
    github_client_id: 
    github_private_key: 

    linkedin_client_id: 
    linkedin_private_key: 

    google_client_id: 
    google_private_key:

  # deployment can be prod or dev, for dev it will relax cookies/CORS so that it can be used by a web app running
  # in localhost with other port (e.g. Angular :4200)
  deployment: "dev"
  #deployment: "prod"

  ## CORS setting for the web API
  CORS:
    dev:
      # allowed CORS origins depending on the deployment mode
      allowed_origins:
        - "http://localhost:4200"
        - "http://0.0.0.0:8050"
      allowed_methods:
        - "OPTIONS"
        - "GET"
        - "PUT"
        - "POST"
        - "DELETE"
        - "HEAD"
      allowed_headers:
        - "X-Requested-With"
        - "Content-Type"
        - "Accept"
        - "Origin"
    prod:
      allowed_origins:
        - "*"
      allowed_methods:
        - "OPTIONS"
        - "GET"
        - "PUT"
        - "POST"
        - "DELETE"
        - "HEAD"
      allowed_headers:
        - "X-Requested-With"
        - "Content-Type"
        - "Accept"
        - "Origin"

## information for sending password reset email, assuming TTL secured SMTP server, keep it secret
smtp:
  host: 
  port:
  account:
  pwd: "*SECRET*"
  # root url where the app is running to generate usable link in the email (e.g. https://somewhere.com/kish/app)
  app_domain: 
